/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.*;
import java.awt.Color;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import model.Kontroler;
import table.model.TableModelKorisnici;
import util.Akcija;
import util.TransferKlasa;

/**
 *
 * @author Matija1
 */
public class AdminForma extends javax.swing.JFrame {

    /**
     * Creates new form AdminForma
     */
    TableModelKorisnici tmk;
    public AdminForma() {
        initComponents();
        srediFormu();
    }
    private List<Korisnik> listaKorisnika;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblKorisnici = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboKriterijum = new javax.swing.JComboBox();
        jtxtFilter = new javax.swing.JTextField();
        jbtResetujFilter = new javax.swing.JButton();
        jbtIzmena = new javax.swing.JButton();
        jbtBrisanje = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtnRadSaLokalima = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtblKorisnici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblKorisnici);

        jLabel2.setText("Kriterijum pretrage:");

        jComboKriterijum.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "KorisnikID", "Ime i prezime", "Email", "Sifra", "Mesto", "Adresa", "Uloga" }));
        jComboKriterijum.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboKriterijumItemStateChanged(evt);
            }
        });

        jtxtFilter.setEditable(false);
        jtxtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFilterActionPerformed(evt);
            }
        });
        jtxtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtFilterKeyReleased(evt);
            }
        });

        jbtResetujFilter.setText("Resetuj filter");
        jbtResetujFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetujFilterActionPerformed(evt);
            }
        });

        jbtIzmena.setText("Sacuvaj izmenu korisnika");
        jbtIzmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtIzmenaActionPerformed(evt);
            }
        });

        jbtBrisanje.setText("Obrisi korisnika");
        jbtBrisanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBrisanjeActionPerformed(evt);
            }
        });

        lblPoruka.setText(" ");

        jButton1.setText("Nazad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnRadSaLokalima.setText("Rad sa lokalima");
        jbtnRadSaLokalima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRadSaLokalimaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtIzmena, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBrisanje, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtResetujFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbtnRadSaLokalima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                    .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnRadSaLokalima)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboKriterijum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtResetujFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtIzmena)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtBrisanje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboKriterijumItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboKriterijumItemStateChanged
        String izbor = jComboKriterijum.getSelectedItem().toString();
        if (izbor.startsWith("Bez")) {
            jtxtFilter.setEditable(false);
            jtxtFilter.setText("");
            srediTabelu(null);
            jtxtFilter.setBackground(Color.lightGray);
        } else {
            jtxtFilter.setEditable(true);
            jtxtFilter.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_jComboKriterijumItemStateChanged

    private void jtxtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFilterActionPerformed

    private void jtxtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtFilterKeyReleased
        String polje = jComboKriterijum.getSelectedItem().toString();
        String filter = jtxtFilter.getText().toLowerCase();
        List<Korisnik> listaTemp = new ArrayList<>();
        for (int i = 0; i < listaKorisnika.size(); i++) {
            listaTemp.add(i, listaKorisnika.get(i));
            
        }
        switch (polje) {
            
            case "KorisnikID":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!(listaKorisnika.get(i).getKorisnikID() + "").contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
            case "Ime i prezime":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!listaKorisnika.get(i).getImePrezime().toLowerCase().contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
            case "Email":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!(listaKorisnika.get(i).getEmail()).contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
            case "Sifra":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!(listaKorisnika.get(i).getSifra()).contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
            case "Mesto":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!(listaKorisnika.get(i).getMesto().getNaziv().toLowerCase()).contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
            case "Adresa":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!(listaKorisnika.get(i).getAdresa().toLowerCase()).contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
            case "Uloga":
                for (int i = listaKorisnika.size() - 1; i >= 0; i--) {
                    if (!(listaKorisnika.get(i).getUloga() + "").contains(filter)) {
                        listaTemp.remove(i);
                    }
                }
                break;
        }
        tmk.setListaKorisnika(listaTemp);
//        srediTabelu(listaKorisnika);
        //        JOptionPane.showMessageDialog(this, "Sistem je nasao zaposlene po zadatoj vrednosti", "Poruka", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jtxtFilterKeyReleased

    private void jbtResetujFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetujFilterActionPerformed
        jComboKriterijum.setSelectedIndex(0);
    }//GEN-LAST:event_jbtResetujFilterActionPerformed

    private void jbtIzmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtIzmenaActionPerformed
        lblPoruka.setText(" ");
        int r = jtblKorisnici.getSelectedRow();
        if (r < 0) {
            lblPoruka.setText("Morate prvo odabrati zaposlenog!");
            return;
        }
        Korisnik k = new Korisnik();
        k.setKorisnikID((int)jtblKorisnici.getValueAt(r, 0));
        k.setImePrezime(jtblKorisnici.getValueAt(r, 1).toString());
        k.setEmail(jtblKorisnici.getValueAt(r, 2).toString());
        k.setSifra(jtblKorisnici.getValueAt(r, 3).toString());
        k.setMesto((Mesto) jtblKorisnici.getValueAt(r, 4));
        k.setAdresa(jtblKorisnici.getValueAt(r, 5).toString());
        k.setUloga((int) jtblKorisnici.getValueAt(r, 7));

        try {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.SACUVAJ_IZMENU_KORISNIKA);
            zahtev.setParametar(k);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            JOptionPane.showMessageDialog(this, "Sistem je uspeo da sacuva izmenu zaposlenog", "Poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtIzmenaActionPerformed

    private void jbtBrisanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBrisanjeActionPerformed

        lblPoruka.setText(" ");
        int r = jtblKorisnici.getSelectedRow();
        if (r < 0) {
            lblPoruka.setText("Morate prvo odabrati zaposlenog!");
            return;
        }
        Korisnik k = new Korisnik();
        k.setKorisnikID((int) jtblKorisnici.getValueAt(r, 0));

        try {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.BRISI_KORISNIKA);
            zahtev.setParametar(k);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            JOptionPane.showMessageDialog(this, "Sistem je uspeo da obrise korisnika", "Poruka", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            lblPoruka.setText("Nije moguce obrisati.");
            return;
        }
        try {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.VRATI_SVE_KORISNIKE);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            List<Korisnik> zap = (List<Korisnik>) odgovor.getRezultat();
            srediTabelu(zap);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem nije uspeo da ucita korisnike.", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtBrisanjeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            UlogovanKorisnik formaUlogovan = new UlogovanKorisnik();
            formaUlogovan.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminForma.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnRadSaLokalimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRadSaLokalimaActionPerformed
        try {
            Kontroler.getINSTANCE().staviUMapu("adminFormaKlijenti", this);
            AdminFormaLokal afl = new AdminFormaLokal();
            afl.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(AdminForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnRadSaLokalimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboKriterijum;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBrisanje;
    private javax.swing.JButton jbtIzmena;
    private javax.swing.JButton jbtResetujFilter;
    private javax.swing.JButton jbtnRadSaLokalima;
    private javax.swing.JTable jtblKorisnici;
    private javax.swing.JTextField jtxtFilter;
    private javax.swing.JLabel lblPoruka;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() {
        setTitle("Admin - Rad sa korisnicima");
        srediTabelu(null);
    }

    private void srediTabelu(List<Korisnik> lk) {
        try {
//            if (lk == null) {
            TransferKlasa zahtev = new TransferKlasa();
            zahtev.setOperacija(Akcija.VRATI_SVE_KORISNIKE);
            Kontroler.getINSTANCE().posalji(zahtev);
            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
            listaKorisnika = (List<Korisnik>) odgovor.getRezultat();
//            } else {
//                listaKorisnika = lk;
//            }
            
            zahtev.setOperacija(Akcija.VRATI_SVA_MESTA);
            Kontroler.getINSTANCE().posalji(zahtev);
            odgovor = Kontroler.getINSTANCE().primi();
            List<Mesto> listaMesta = (List<Mesto>) odgovor.getRezultat();
//            for (int i = 0; i < listaKorisnika.size(); i++) {
//                listaMesta.add(i, listaKorisnika.get(i).getMesto());
//                
//            }

            tmk = new TableModelKorisnici(listaKorisnika);
            jtblKorisnici.setModel(tmk);
            TableColumnModel tcm = jtblKorisnici.getColumnModel();
            TableColumn tc = tcm.getColumn(4);
            JComboBox jcb = new JComboBox();

            jcb.setModel(new DefaultComboBoxModel(listaMesta.toArray()));
            tc.setCellEditor(new DefaultCellEditor(jcb));

            jtblKorisnici.setAutoCreateRowSorter(true);
            jtblKorisnici.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jtblKorisnici.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }
}
