/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import model.Kontroler;
import model.sesija.Sesija;
import util.Akcija;
import util.TransferKlasa;

/**
 *
 * @author Matija1
 */
public class Glavna extends javax.swing.JFrame {

    /**
     * Creates new form UlogujSe
     */
    public Glavna() {
        initComponents();
        try {
            Kontroler.getINSTANCE().staviUMapu("glavna", this);
//            Kontroler.getINSTANCE().staviUMapu("adminUlogovan", false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMKorisnik = new javax.swing.JMenu();
        jMIKorisnik = new javax.swing.JMenuItem();
        jMILokal = new javax.swing.JMenuItem();
        jMRegistrujSe = new javax.swing.JMenu();
        jMIRegKorisnik = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Dobrodosli. ");

        jLabel2.setText("Ulogujte se da bi videli gde u gradu ima mesta,");

        jLabel3.setText("ili se registrujte aako nemate korisnicki nalog.");

        jMKorisnik.setText("Uloguj se");

        jMIKorisnik.setText("Kao korisnik");
        jMIKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIKorisnikActionPerformed(evt);
            }
        });
        jMKorisnik.add(jMIKorisnik);

        jMILokal.setText("Kao lokal");
        jMILokal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMILokalActionPerformed(evt);
            }
        });
        jMKorisnik.add(jMILokal);

        jMenuBar1.add(jMKorisnik);

        jMRegistrujSe.setText("Registruj se");

        jMIRegKorisnik.setText("Kao korisnik");
        jMIRegKorisnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIRegKorisnikActionPerformed(evt);
            }
        });
        jMRegistrujSe.add(jMIRegKorisnik);

        jMenuBar1.add(jMRegistrujSe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIKorisnikActionPerformed
        UlogujSeKorisnik formaLogKorisnik = new UlogujSeKorisnik();
        this.setVisible(false);
        formaLogKorisnik.setVisible(true);
    }//GEN-LAST:event_jMIKorisnikActionPerformed

    private void jMILokalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMILokalActionPerformed
        UlogujSeLokal formaLogLokal = new UlogujSeLokal();
        this.setVisible(false);
        formaLogLokal.setVisible(true);
    }//GEN-LAST:event_jMILokalActionPerformed

    private void jMIRegKorisnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIRegKorisnikActionPerformed
        RegistrujSeKorisnik regForma = new RegistrujSeKorisnik();
        this.setVisible(false);
        regForma.setVisible(true);
    }//GEN-LAST:event_jMIRegKorisnikActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        try { //ovaj dogadjaj se nekad okida a nekad ne, pa se desava da server zakuca zbog toga
//            Kontroler.getINSTANCE().kraj();
//            dispose();
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, e.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
//        }
    }//GEN-LAST:event_formWindowClosing
        
          
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Glavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Glavna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMIKorisnik;
    private javax.swing.JMenuItem jMILokal;
    private javax.swing.JMenuItem jMIRegKorisnik;
    private javax.swing.JMenu jMKorisnik;
    private javax.swing.JMenu jMRegistrujSe;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    
}
