/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Korisnik;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Kontroler;
import model.sesija.Sesija;

/**
 *
 * @author Matija1
 */
public class UlogujSeKorisnik extends javax.swing.JFrame {

    /**
     * Creates new form UlogujSeKorisnik
     */
    public UlogujSeKorisnik() {
        setTitle("Login korisnik");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblImePrezime = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jbtnNazad = new javax.swing.JButton();
        jlblImePrezime1 = new javax.swing.JLabel();
        jbtnUlogujSe = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblImePrezime.setText("Email:");

        jbtnNazad.setText("Nazad");
        jbtnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNazadActionPerformed(evt);
            }
        });

        jlblImePrezime1.setText("Sifra:");

        jbtnUlogujSe.setText("Uloguj se");
        jbtnUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUlogujSeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnNazad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(jbtnUlogujSe))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblImePrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblImePrezime1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jPassword))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblImePrezime)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblImePrezime1)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnUlogujSe)
                    .addComponent(jbtnNazad))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNazadActionPerformed
        try {
            Glavna glavna = (Glavna) Kontroler.getINSTANCE().vratiIzMape("glavna");
            glavna.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(UlogujSeKorisnik.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnNazadActionPerformed

    private void jbtnUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUlogujSeActionPerformed
        
            String kEmail = jtxtEmail.getText();
            char[] kS = jPassword.getPassword();
            String kSifra = "";
            for (int i = 0; i < kS.length; i++) {
                kSifra += kS[i];
            }

            if (kEmail.isEmpty() || kSifra.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Greska", "Email ili šifra nisu dobro uneti! Pokušajte ponovo!", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    Korisnik korisnik = (Korisnik)Kontroler.getINSTANCE().ulogujSe(kEmail, kSifra, "korisnici");

                    if (korisnik != null) {
                        Kontroler.getINSTANCE().staviUMapu("korisnik", korisnik);
                        UlogovanKorisnik formaUlog = new UlogovanKorisnik();
                        formaUlog.setVisible(true);
                        this.dispose();
                        
                    } else {
                        JOptionPane.showMessageDialog(this, "Email ili šifra nisu dobro uenti! Pokušajte ponovo!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                        
                    }
                } catch (Exception ex) {
                    Logger.getLogger(UlogujSeKorisnik.class.getName()).log(Level.SEVERE, null, ex);
//                    JOptionPane.showMessageDialog(this, "Greska", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
//                    return;
                }
            }
        
    }//GEN-LAST:event_jbtnUlogujSeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UlogujSeKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UlogujSeKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UlogujSeKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UlogujSeKorisnik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UlogujSeKorisnik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JButton jbtnNazad;
    private javax.swing.JButton jbtnUlogujSe;
    private javax.swing.JLabel jlblImePrezime;
    private javax.swing.JLabel jlblImePrezime1;
    private javax.swing.JTextField jtxtEmail;
    // End of variables declaration//GEN-END:variables
}
