/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Lokal;
import domen.Mesto;
import domen.Post;
import domen.TipLokala;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import model.Kontroler;
import model.sesija.Sesija;
import table.model.TableModelLokali;
import table.model.TableModelPostovi;
import util.Akcija;
import util.TransferKlasa;

/**
 *
 * @author Matija1
 */
public class UnosPostovaLokal extends javax.swing.JFrame {

    /**
     * Creates new form UnosPostovaAdmin
     */
    TableModelPostovi tmp;
    public UnosPostovaLokal() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jbtnBrisi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jbtnSacuvaj = new javax.swing.JButton();
        jtxSepare = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbtnZapamti = new javax.swing.JButton();
        jtxtPostID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtnResetuj = new javax.swing.JButton();
        jtxtStoloviZaDvoje = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPostovi = new javax.swing.JTable();
        jbtnNazad = new javax.swing.JButton();
        jtxtStoloviZaCetvoro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtATekst = new javax.swing.JTextArea();
        errObrisi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Stolovi za cetvoro:");

        jbtnBrisi.setText("Obrisi post");
        jbtnBrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBrisiActionPerformed(evt);
            }
        });

        jLabel4.setText("Separei:");

        jbtnSacuvaj.setText("Sacuvaj postove");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jLabel7.setText("Tekst:");

        jLabel9.setText("ID posta:");

        jbtnZapamti.setText("Zapamti post");
        jbtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZapamtiActionPerformed(evt);
            }
        });

        jLabel2.setText("Stolovi za dvoje:");

        jbtnResetuj.setText("Resetuj polja forme");
        jbtnResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetujActionPerformed(evt);
            }
        });

        jtblPostovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblPostovi);

        jbtnNazad.setText("Nazad");
        jbtnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNazadActionPerformed(evt);
            }
        });

        jtxtATekst.setColumns(20);
        jtxtATekst.setRows(5);
        jScrollPane2.setViewportView(jtxtATekst);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnZapamti, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnResetuj, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnBrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(errObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                                .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(174, 174, 174))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtPostID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtStoloviZaCetvoro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtxSepare, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtStoloviZaDvoje, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jScrollPane2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(247, 247, 247)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPostID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtStoloviZaDvoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtStoloviZaCetvoro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxSepare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtnZapamti)
                        .addComponent(jbtnBrisi)
                        .addComponent(jbtnSacuvaj))
                    .addComponent(errObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnResetuj)
                    .addComponent(jbtnNazad))
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBrisiActionPerformed
        try {
            tmp.obrisi(jtblPostovi.getSelectedRow());
            errObrisi.setText("");
        } catch (Exception e) {
            errObrisi.setText("Morate odabrati post!");
        }
    }//GEN-LAST:event_jbtnBrisiActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            List<Post> listaPostova = tmp.vratiListuPostova();

            //            if (Kontroler.getINSTANCE().vratiIzMape("sk").equals("unosAviona")) {
                //                for (int i = 0; i < listaLokala.size(); i++) {
                    TransferKlasa zahtev = new TransferKlasa();
                    zahtev.setOperacija(Akcija.NOVI_POSTOVI);
                    zahtev.setParametar(listaPostova);
                    Kontroler.getINSTANCE().posalji(zahtev);
                    TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
                    boolean ubacen = (boolean) odgovor.getRezultat();
                    JOptionPane.showMessageDialog(this, "Sistem je zapamtio podatke o novim postovima.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
                    //                }
                //            }
            //            if (Kontroler.getINSTANCE().vratiIzMape("sk").equals("izmenaAviona")) {
                //                tmp.sacuvaj();
                //                JOptionPane.showMessageDialog(this, "Sistem je uspeo da izmeni avion.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
                //            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti novi post.", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jbtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZapamtiActionPerformed
        String postIDS = jtxtPostID.getText().trim();
        String stoloviZaDvojeS = jtxtStoloviZaDvoje.getText().trim();
        String stoloviZaCetvoroS = jtxtStoloviZaCetvoro.getText().trim();
        String separeS = jtxSepare.getText().trim();
        Lokal l = (Lokal) Sesija.vratiInstancu().getMapa().get("lokal");
        String status = jtxtATekst.getText().trim();

        String tekstREGEX = ".+";
        String brojREGEX = "[0-9]+";

        if (!postIDS.matches(brojREGEX)) {
            JOptionPane.showMessageDialog(this, "Greska!", "Morate uneti id lokala!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!stoloviZaDvojeS.matches(brojREGEX)) {
            JOptionPane.showMessageDialog(this, "Greska!", "Morate popuniti email polje sa validnom adresom!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!stoloviZaCetvoroS.matches(brojREGEX)) {
            JOptionPane.showMessageDialog(this, "Greska!", "Morate uneti naziv!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!separeS.matches(brojREGEX)) {
            JOptionPane.showMessageDialog(this, "Greska!", "Morate uneti sifru!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!status.matches(tekstREGEX)) {
            JOptionPane.showMessageDialog(this, "Greska!", "Morate uneti adresu!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int postID = Integer.parseInt(postIDS);
        int stoloviZaDvoje = Integer.parseInt(stoloviZaDvojeS);
        int stoloviZaCetvoro = Integer.parseInt(stoloviZaCetvoroS);
        int separe = Integer.parseInt(separeS);
        Date d = new Date();
        Post p;
        try {
            p = new Post(postID,stoloviZaDvoje, stoloviZaCetvoro, separe, status, d, l);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        }

        tmp.dodajNoviRed(p);
        JOptionPane.showMessageDialog(this, "Sistem je kreirao novi lokal.", "Poruka", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbtnZapamtiActionPerformed

    private void jbtnResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetujActionPerformed
        resetujPoljaForme();
    }//GEN-LAST:event_jbtnResetujActionPerformed

    private void jbtnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNazadActionPerformed
        UlogovanLokal ul = new UlogovanLokal();
        ul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNazadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.htmp 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnosPostovaLokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnosPostovaLokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnosPostovaLokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnosPostovaLokal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnosPostovaLokal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errObrisi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnBrisi;
    private javax.swing.JButton jbtnNazad;
    private javax.swing.JButton jbtnResetuj;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnZapamti;
    private javax.swing.JTable jtblPostovi;
    private javax.swing.JTextField jtxSepare;
    private javax.swing.JTextArea jtxtATekst;
    private javax.swing.JTextField jtxtPostID;
    private javax.swing.JTextField jtxtStoloviZaCetvoro;
    private javax.swing.JTextField jtxtStoloviZaDvoje;
    // End of variables declaration//GEN-END:variables

private void srediFormu() {
        setTitle("Unos postova");
        srediTabelu();
    }

    private void srediTabelu() {
        try {
            TransferKlasa zahtev = new TransferKlasa();
            
            
//            zahtev.setOperacija(Akcija.VRATI_SVE_LOKALE);
//            Kontroler.getINSTANCE().posalji(zahtev);
//            TransferKlasa odgovor = Kontroler.getINSTANCE().primi();
//            List<Lokal> listaLokala = (List<Lokal>) odgovor.getRezultat();
//            jcmbLokali.setModel(new DefaultComboBoxModel(listaLokala.toArray()));
            tmp = new TableModelPostovi();
            tmp.setLokalEditable(false);
            jtblPostovi.setModel(tmp);
//            TableColumnModel tcm = jtblPostovi.getColumnModel();
//            TableColumn tc = tcm.getColumn(1);
//            JComboBox jcb = new JComboBox();

//            jcb.setModel(new DefaultComboBoxModel(listaLokala.toArray()));
//            tc.setCellEditor(new DefaultCellEditor(jcb));
//            
//            tc = tcm.getColumn(6);
//            JComboBox jcb1 = new JComboBox();
//            
//            jcb1.setModel(new DefaultComboBoxModel(listaTipovaLokala.toArray()));
//            tc.setCellEditor(new DefaultCellEditor(jcb1));
//            
//            jcmbMesta.setModel(new DefaultComboBoxModel(listaMesta.toArray()));
//            jcmbTip.setModel(new DefaultComboBoxModel(listaTipovaLokala.toArray()));
            
            jtblPostovi.setAutoCreateRowSorter(true);
            jtblPostovi.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jtblPostovi.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void resetujPoljaForme() {
        jtxtPostID.setText("");
        jtxtStoloviZaDvoje.setText("");
        jtxtStoloviZaCetvoro.setText("");
        jtxSepare.setText("");
        jtxtATekst.setText("");

        resetujErrorLabele();
    }

    private void resetujErrorLabele() {
        errObrisi.setText("");
    }

}
